SELECT * FROM USER;

CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId VARCHAR(30) NOT NULL,
    pw VARCHAR(50) NOT NULL,
    name VARCHAR(20) NOT NULL,
    email VARCHAR(100) NOT NULL,
    contact VARCHAR(20) NOT NULL
);